// <auto-generated/>

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("FeaturesViewEngine")]
[assembly: AssemblyVersion("1.1.2")]
[assembly: AssemblyFileVersion("1.1.2")]
[assembly: ComVisible(false)]
[assembly: AssemblyCopyright("Copyright © Maris Krivtezs 2018")]
[assembly: AssemblyCompany("Maris Krivtezs")]
[assembly: AssemblyDescription("View Engine which enables feature folder support for MVC (prior .NET Core).")]
[assembly: AssemblyTitle("FeaturesViewEngine")]

namespace System
{
    internal static class AssemblyVersionInformation
    {
        internal const string AssemblyProduct = "FeaturesViewEngine";
        internal const string AssemblyVersion = "1.1.2";
        internal const string AssemblyFileVersion = "1.1.2";
        internal const bool ComVisible = false;
        internal const string AssemblyCopyright = "Copyright © Maris Krivtezs 2018";
        internal const string AssemblyCompany = "Maris Krivtezs";

        internal const string AssemblyDescription =
            "View Engine which enables feature folder support for MVC (prior .NET Core).";

        internal const string AssemblyTitle = "FeaturesViewEngine";
    }
}